version: "3.9"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      - PORT=${PORT:-4000}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
      - REDIS_URL=${REDIS_URL:-}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-60}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN:-*}
    ports:
      - "${PORT:-4000}:4000"
    depends_on:
      - redis
    profiles:
      - ""
      - redis

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    profiles:
      - redis

volumes:
  redis-data:
